### ISSUE TITLE
Grafana administrator

### ISSUE THREAD

**Issue by jellium** [YunoHost-Apps/grafana_ynh#1]
During installation, no Grafana administrator can be specified. Therefore after first login, one can create and manage organizations but without system-wide permissions (see http://docs.grafana.org/reference/admin/#grafana-administrators). 

Thanks a lot for the nice package by the way! :smile:

**Comment by JimboJoe** [comment]
I totally forgot that part!
I will probably have to ask for the administrator's name during installation, as you suggest.

As a workaround, in grafana database, you can : 
- delete your user, and for admin entry, change `login` to your login AND `email` to your email address.
- or simpler, set the `is_admin` field to 1 for your user.
Thanks for reporting!
