### ISSUE TITLE
Access InfluxDB from the outside.

### ISSUE THREAD

**Issue by optikfluffel** [YunoHost-Apps/grafana_ynh#10]
Hi, is there a way to access the included InfluxDB from another computer?

Thanks.

**Comment by JimboJoe** [comment]
Hi,
As for almost every services provided by YunoHost (e.g. LDAP) or YunoHost packages, services are usually not reachable from outside if it's not required (for security reasons).
I guess you can play with InfluxDB and/or iptables configuration to reach your needs, but in my opinion it's far beyond the scope of this package.

**Comment by JimboJoe** [comment]
I'm closing this issue for now. Don't hesitate to re-open it if needed :wink:
