### ISSUE TITLE
Service needs to be restart after each reboot

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/grafana_ynh#12]
Hi
I get 502 error after each reboot. Restarting the grafana services brings back the grafana interface. Is this issue related to my instance only?

**Comment by JimboJoe** [comment]
Can't reproduce your issue with my setup (grafana 4.6.2). What's your version of grafana?

**Comment by anmol26s** [comment]
My version is 4.6.2 too

**Comment by JimboJoe** [comment]
What does `systemctl|grep grafana-server` says?

**Comment by anmol26s** [comment]
```
grafana-server.service                                                                  
 loaded active running   Grafana instance
```

**Comment by JimboJoe** [comment]
So the service is enabled and started at system boot.
Any relevant log in `/var/log/grafana/grafana.log`?

**Comment by JimboJoe** [comment]
As nothing happened here since a few months, I consider you solved you problem and I close this issue :wink:  
Please feel free to reopen it if there's more to do!
