### ISSUE TITLE
Can't install grafana_ynh when influx2 already installed (by scrutiny_ynh)

### ISSUE THREAD

**Issue by arthurlutz** [YunoHost-Apps/grafana_ynh#122]
### Describe the bug

Grafana yunohost package install fails when scrutiny_ynh https://github.com/YunoHost-Apps/scrutiny_ynh is already installed (it installs influx2 debian package) 

### Context

- Hardware: *Old computer*
- YunoHost version: 11.2.5 (stable).
- I have access to my server: Through SSH | through the webadmin | direct access via keyboard / screen
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - If yes, please explain: various install tweaks
- Using, or trying to install package version/branch:

### Steps to reproduce

- Install https://github.com/YunoHost-Apps/scrutiny_ynh
- Try to install https://github.com/YunoHost-Apps/grafana_ynh
- Error occurs

### Expected behavior

For both applications to be installable side by side. I can see there a number of issues about upgrading to influx2 maybe this is a solution to this problem. see #52 

### Logs

https://paste.yunohost.org/raw/zevajafupu

**Comment by OniriCorpe** [comment]
see: https://github.com/YunoHost-Apps/scrutiny_ynh/issues/13#issuecomment-1799814746
