### ISSUE TITLE
Ipv4 graph empty for eth0 

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/grafana_ynh#13]
Hi
I have ipv4 static ip at eth0. The netdata shows the live logs for it, but grafana shows empty graph for it.

**Comment by JimboJoe** [comment]
You may try with the latest default NetData dashboard available [here](https://grafana.com/dashboards/3305). If the problems persists, maybe there has been a change in the parameter name that hasn't been taken into account into this default dashboard.

**Comment by anmol26s** [comment]
I don't know why but I my ipv4 matrix "From" value was `netdata.system.ipv4.OutOctets` for both receiving and sending. Changing the value to `netdata.system.ipv4.received ` and `netdata.system.ipv4.sent ` solved the problem.
By the way how can I keep check the times when my internet goes down?

**Comment by lapineige** [comment]
For information, I had exactly the same issue, and same solution.
