### ISSUE TITLE
Unclean uninstall

### ISSUE THREAD

**Issue by Vitriia** [YunoHost-Apps/grafana_ynh#16]
Hi, 
when i uninstall grafana and install him back. Metrics are still stored and there. How can i do a clean uninstall of grafana ?

**Comment by JimboJoe** [comment]
It seems to be the default behavior of the influxdb package when it's uninstalled: leave the databases. I guess you need to purge the influxdb package if you want to get rid of the databases.
I wouldn't do that in the YunoHost package, as we don't want users to loose their data, though.

**Comment by JimboJoe** [comment]
I'm assuming my answer was satisfying. Please feel free to reopen if that wasn't the case :wink:
