### ISSUE TITLE
Cannot login after logout

### ISSUE THREAD

**Issue by jellium** [YunoHost-Apps/grafana_ynh#2]
After installation and first login, I tried to logout from Grafana from Grafana top-right-hand corner menu.

It brought me to a page saying:

> Server side error :(
> Failed to sync user

Logging out from and logging in back to YunoHost does not solve the problem. No means to log in Grafana is available. :(

**Comment by JimboJoe** [comment]
I can't reproduce your issue on my default installation (x86_64, private installation): when I log out, I get brought to the login page, and I can still login via the form or from the YunoHost menu.

Could you please give more information on your setup? Could you please provide your /var/log/grafana/grafana.org file?

Thanks!

**Comment by jellium** [comment]
Here is the log associated to the error:

> t=2017-03-04T15:01:29+0100 lvl=eror msg="Failed to sync user" logger=context error="Cannot remove last organization admin"
> t=2017-03-04T15:01:29+0100 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=500 remote_addr=my-ip time_ms=10ns size=715

**Comment by JimboJoe** [comment]
Did you try to update the grafana user table by yourself?

**Comment by jellium** [comment]
No I didn't.
I created an Organization (hence there were 2, the main one and that one I created), renamed the main organization, and finally logged out from Grafana.

**Comment by JimboJoe** [comment]
Reproduced with your instructions.
Seems like a Grafana bug that dislikes creating orgs through UI when integrating LDAP... See explanation [here](https://github.com/grafana/grafana/issues/2940#issuecomment-147735355)

For now, I don't see any other solution  for you than than deleting your newly created organization in the `org` table in the Grafana database.
I may remove the Org creation functionality if I don't get a precise answer on Grafana side.
