### ISSUE TITLE
Network error: Bad gateway (502)

### ISSUE THREAD

**Issue by stemy2** [YunoHost-Apps/grafana_ynh#20]
Hello,

All my netdata graphs are empty because of the error mentioned in the title. And i don't understand what did i do wrong.

**Comment by JimboJoe** [comment]
Can you try to launch `systemctl restart grafana-server` and share what `systemctl status grafana-server` returns?

**Comment by JimboJoe** [comment]
Closing as you seem to have fixed your issue. Don't hesitate to reopen if you want :wink:
