### ISSUE TITLE
Install additional Grafana-Addon

### ISSUE THREAD

**Issue by EulenspiegelTill** [YunoHost-Apps/grafana_ynh#37]
### Describe the bug

*Trying to install an Grafana Plugin manualy*

### Context

- Hardware: *Raspberry Pi at home*
- YunoHost version: 4.3.4.1
- I have access to my server: Through SSH & through the webadmin 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch:

### Steps to reproduce

try to install an addon manualy, but i'm a bit lost betweet yunohost and the grafana installation. No clue how to connect with the grafana instance or to get the correct read/write access.

Any tipps or suggestions?

https://grafana.com/docs/grafana/latest/plugins/installation/

https://github.com/akenza-io/grafana-connector-v3/releases

**Comment by matthias4217** [comment]
The `grafana-cli` is located here : `/usr/share/grafana/bin/grafana-cli`. Thus, if you need to use it to install a plugin, you can run `/usr/share/grafana/bin/grafana-cli plugins install <plugin name>`. Afterwards, you will need to restart grafana using `sudo yunohost service restart grafana-server`.
