### ISSUE TITLE
[Security] High severity in Grafana shipped version

### ISSUE THREAD

**Issue by nathanael-h** [YunoHost-Apps/grafana_ynh#38]
From : https://grafana.com/blog/2021/12/07/grafana-8.3.1-8.2.7-8.1.8-and-8.0.7-released-with-high-severity-security-fix/
### Describe the bug

*We shipp 8.06, the is a high severity fix available as 8.0.7*
https://github.com/grafana/grafana/blob/main/docs/sources/release-notes/release-notes-8-0-7.md

**Comment by biva** [comment]
I see that the current version is 8.3.3, should this issue be closed @nathanael-h ?

**Comment by nathanael-h** [comment]
yes
