### ISSUE TITLE
Validate quality level 4 conformance

### ISSUE THREAD

**Issue by JimboJoe** [YunoHost-Apps/grafana_ynh#4]
This application should be reviewed by the YunoHost Apps group to assess quality level 4 conformance.
The user integration is done through:
* [LDAP](http://docs.grafana.org/installation/configuration/#auth-ldap): code justification [here](https://github.com/YunoHost-Apps/grafana_ynh/blob/5a89c5fe6f1e04694dbd593143fa66c0fd5d5e6d/scripts/install#L128-L131)
* [HTTP authentication](http://docs.grafana.org/installation/configuration/#auth-proxy): code justification [here](https://github.com/YunoHost-Apps/grafana_ynh/blob/5a89c5fe6f1e04694dbd593143fa66c0fd5d5e6d/scripts/install#L127)

**Comment by maniackcrudelis** [comment]
I haven't tested, but if ldap and http auth work, it's ok for me.
