### ISSUE TITLE
Validate quality level 5 conformance

### ISSUE THREAD

**Issue by JimboJoe** [YunoHost-Apps/grafana_ynh#5]
This level needs to be formally assessed as there is one residual warning stated by package_linter:
```
>>>> RESTORE SCRIPT <<<<
✔ All commands are prefix with "sudo".
✔ Only helpers are used
✔ no 'exit' command found: 'ynh_die' helper is possibly used
✘ At line 27 'ynh_die' or 'exit' command is executed with system modification before.
 This system modification is an issue if a verification exit the script.
 You should move this verification before any system modification.
✔ set -eu is present at beginning of file
✔ Argument retrieval from manifest seems to be done with environement variables
```
The detected offended system modification is this one:
```
# Fix permissions
sudo chmod a+rx ./conf_grafana/_common.sh
```
which only changes rights on an archive restoration temporary file. Btw, this is a workaround that won't be needed any more after [this change](https://github.com/YunoHost/yunohost/pull/246) is merged into YunoHost stable version.

**Comment by maniackcrudelis** [comment]
Ok for me.
But have you really need to add 'x' permission to this script?

**Comment by JimboJoe** [comment]
You're right, the 'x' permission is not needed to source the file. But it still needs the 'r' permission...
The weird fact is that it doesn't need any permission in package_check environment, but the read permission is mandatory on my production server (latest YunoHost version as well).
