### ISSUE TITLE
Upgrade doesn't work

### ISSUE THREAD

**Issue by JimboJoe** [YunoHost-Apps/grafana_ynh#7]
Upgrade is broken due to new custom port setting at installation.
@nemsia I think we forgot to test that part :-)

A possible plan:

- set the port in the application settings during installation
- retrieve that port setting during upgrade; if not set, set to 3000
- make the string substitution in nginx.conf as you did in install script

Could you possibly make a PR to fix that part?
(Don't forget you can now create a branch in the official repository ;-)
Thanks!

**Comment by nemsia** [comment]
OK, i work on it.

**Comment by nemsia** [comment]
Fixed by this https://github.com/YunoHost-Apps/grafana_ynh/pull/8
