### ISSUE TITLE
Netdata conf

### ISSUE THREAD

**Issue by landrain** [YunoHost-Apps/grafana_ynh#9]
hello,

i have problem with the data. netdata send metric to influxdb example: metric in influxdb divide not summary. like cpu.mysld, cpu.httpd

i want make data in influxdb only cpu value ( summary all cpu servicec on the server).

Please help me what i must do. thank you

**Comment by JimboJoe** [comment]
There's a CPU Utilization panel in the default NetData dashboard provided with the package. Have you checked that?

**Comment by JimboJoe** [comment]
I'm closing this issue for now. Don't hesitate to re-open it if needed :wink:
